# Generated by Django 4.2.5 on 2024-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0003_remove_interviewschedule_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
