# Generated by Django 4.2.5 on 2024-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tpoapi', '0005_questions_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='no',
            field=models.PositiveIntegerField(),
        ),
    ]
